import json, glob, os
art = {os.path.basename(f)[:-5]: json.load(open(f)) for f in sorted(glob.glob('out/*.json'))}
js = ('// origami-art.js -- GENERATED by origami/gen.py from the traced cast (puppet-refs/cast).\n'
      '// Pre-cut papercraft animal parts for creatures.js (see "origami puppets" there). Do not edit by hand.\n'
      'window.ORIGAMI_ART = ' + json.dumps(art, separators=(',', ':')) + ';\n')
open('/home/claude/v2/js/origami-art.js', 'w').write(js)
print(len(js) // 1024, 'KB', list(art))
